@server=http://localhost:4004
@username=alice
@password=


### Products
# @name Products_GET
GET {{server}}/odata/v4/procurement/Products
Authorization: Basic {{username}}:{{password}}


### Products
# @name Products_POST
POST {{server}}/odata/v4/procurement/Products
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "product_id": 6874518,
  "name": "name-6874518",
  "category": "category-6874518",
  "safety_stock_level": 44.607606119568835,
  "current_stock_level": 52.88955616597555
}


### Products
# @name Products_PATCH
PATCH {{server}}/odata/v4/procurement/Products/6874518
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "product_id": 6874518,
  "name": "name-6874518",
  "category": "category-6874518",
  "safety_stock_level": 44.607606119568835,
  "current_stock_level": 52.88955616597555
}


### Products
# @name Products_DELETE
DELETE {{server}}/odata/v4/procurement/Products/6874518
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Vendors
# @name Vendors_GET
GET {{server}}/odata/v4/procurement/Vendors
Authorization: Basic {{username}}:{{password}}


### Vendors
# @name Vendors_POST
POST {{server}}/odata/v4/procurement/Vendors
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "vendor_id": 26844173,
  "name": "name-26844173",
  "risk_rating": 6,
  "is_compliant": false,
  "contact_name": "contact_name-26844173",
  "contact_email": "contact_email-26844173",
  "country": {
    "country_id": 741019
  },
  "product": {
    "product_id": 6874518
  }
}


### Vendors
# @name Vendors_PATCH
PATCH {{server}}/odata/v4/procurement/Vendors/26844173
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "vendor_id": 26844173,
  "name": "name-26844173",
  "risk_rating": 6,
  "is_compliant": false,
  "contact_name": "contact_name-26844173",
  "contact_email": "contact_email-26844173",
  "country": {
    "country_id": 741019
  },
  "product": {
    "product_id": 6874518
  }
}


### Vendors
# @name Vendors_DELETE
DELETE {{server}}/odata/v4/procurement/Vendors/26844173
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Countries
# @name Countries_GET
GET {{server}}/odata/v4/procurement/Countries
Authorization: Basic {{username}}:{{password}}


### Countries
# @name Countries_POST
POST {{server}}/odata/v4/procurement/Countries
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "country_id": 741019,
  "country_name": "country_name-741019"
}


### Countries
# @name Countries_PATCH
PATCH {{server}}/odata/v4/procurement/Countries/741019
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "country_id": 741019,
  "country_name": "country_name-741019"
}


### Countries
# @name Countries_DELETE
DELETE {{server}}/odata/v4/procurement/Countries/741019
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Tariffs
# @name Tariffs_GET
GET {{server}}/odata/v4/procurement/Tariffs
Authorization: Basic {{username}}:{{password}}


### Tariffs
# @name Tariffs_POST
POST {{server}}/odata/v4/procurement/Tariffs
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "tariff_id": 27256921,
  "current_tariff_rate": 85.21208996646858,
  "effective_date": "2010-12-23T00:00:00.000Z",
  "expiring_date": "2022-10-04T00:00:00.000Z",
  "country": {
    "country_id": 741019
  },
  "product": {
    "product_id": 6874518
  }
}


### Tariffs
# @name Tariffs_PATCH
PATCH {{server}}/odata/v4/procurement/Tariffs/27256921
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "tariff_id": 27256921,
  "current_tariff_rate": 85.21208996646858,
  "effective_date": "2010-12-23T00:00:00.000Z",
  "expiring_date": "2022-10-04T00:00:00.000Z",
  "country": {
    "country_id": 741019
  },
  "product": {
    "product_id": 6874518
  }
}


### Tariffs
# @name Tariffs_DELETE
DELETE {{server}}/odata/v4/procurement/Tariffs/27256921
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### VendorContracts
# @name VendorContracts_GET
GET {{server}}/odata/v4/procurement/VendorContracts
Authorization: Basic {{username}}:{{password}}


### VendorContracts
# @name VendorContracts_POST
POST {{server}}/odata/v4/procurement/VendorContracts
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "contract_id": 8690223,
  "start_date": "2011-07-30T00:00:00.000Z",
  "end_date": "2010-06-11T00:00:00.000Z",
  "minimum_order_quantity": 51,
  "volume_discount_tiers": "volume_discount_tiers-8690223",
  "penalty_clause": "penalty_clause-8690223",
  "vendor": {
    "vendor_id": 26844173
  },
  "product": {
    "product_id": 6874518
  }
}


### VendorContracts
# @name VendorContracts_PATCH
PATCH {{server}}/odata/v4/procurement/VendorContracts/8690223
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "contract_id": 8690223,
  "start_date": "2011-07-30T00:00:00.000Z",
  "end_date": "2010-06-11T00:00:00.000Z",
  "minimum_order_quantity": 51,
  "volume_discount_tiers": "volume_discount_tiers-8690223",
  "penalty_clause": "penalty_clause-8690223",
  "vendor": {
    "vendor_id": 26844173
  },
  "product": {
    "product_id": 6874518
  }
}


### VendorContracts
# @name VendorContracts_DELETE
DELETE {{server}}/odata/v4/procurement/VendorContracts/8690223
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### PurchaseOrders
# @name PurchaseOrders_GET
GET {{server}}/odata/v4/procurement/PurchaseOrders
Authorization: Basic {{username}}:{{password}}


### PurchaseOrders
# @name PurchaseOrders_POST
POST {{server}}/odata/v4/procurement/PurchaseOrders
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "po_id": 12460015,
  "status": "status-12460015",
  "expected_delivery_date": "2002-10-30T00:00:00.000Z",
  "received_date": "2022-04-01T00:00:00.000Z",
  "disruption_reason": "disruption_reason-12460015",
  "product_quantity": 3,
  "po_total": 78.00335112771533,
  "allocation": {
    "allocation_id": 18507107
  },
  "product": {
    "product_id": 6874518
  },
  "vendor": {
    "vendor_id": 26844173
  }
}


### PurchaseOrders
# @name PurchaseOrders_PATCH
PATCH {{server}}/odata/v4/procurement/PurchaseOrders/12460015
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "po_id": 12460015,
  "status": "status-12460015",
  "expected_delivery_date": "2002-10-30T00:00:00.000Z",
  "received_date": "2022-04-01T00:00:00.000Z",
  "disruption_reason": "disruption_reason-12460015",
  "product_quantity": 3,
  "po_total": 78.00335112771533,
  "allocation": {
    "allocation_id": 18507107
  },
  "product": {
    "product_id": 6874518
  },
  "vendor": {
    "vendor_id": 26844173
  }
}


### PurchaseOrders
# @name PurchaseOrders_DELETE
DELETE {{server}}/odata/v4/procurement/PurchaseOrders/12460015
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### AllocationResult
# @name AllocationResult_GET
GET {{server}}/odata/v4/procurement/AllocationResult
Authorization: Basic {{username}}:{{password}}


### AllocationResult
# @name AllocationResult_POST
POST {{server}}/odata/v4/procurement/AllocationResult
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "allocation_id": 18507107,
  "allocated_quantity": 28,
  "total_effective_cost": 56.388744158563064,
  "rationale_summary": "rationale_summary-18507107",
  "created_at": "2015-07-05T00:00:00.000Z",
  "suggested_by_agent": false,
  "scenario": {
    "scenario_id": 21660383
  },
  "vendor": {
    "vendor_id": 26844173
  },
  "product": {
    "product_id": 6874518
  }
}


### AllocationResult
# @name AllocationResult_PATCH
PATCH {{server}}/odata/v4/procurement/AllocationResult/18507107
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "allocation_id": 18507107,
  "allocated_quantity": 28,
  "total_effective_cost": 56.388744158563064,
  "rationale_summary": "rationale_summary-18507107",
  "created_at": "2015-07-05T00:00:00.000Z",
  "suggested_by_agent": false,
  "scenario": {
    "scenario_id": 21660383
  },
  "vendor": {
    "vendor_id": 26844173
  },
  "product": {
    "product_id": 6874518
  }
}


### AllocationResult
# @name AllocationResult_DELETE
DELETE {{server}}/odata/v4/procurement/AllocationResult/18507107
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### OptimizationScenario
# @name OptimizationScenario_GET
GET {{server}}/odata/v4/procurement/OptimizationScenario
Authorization: Basic {{username}}:{{password}}


### OptimizationScenario
# @name OptimizationScenario_POST
POST {{server}}/odata/v4/procurement/OptimizationScenario
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "scenario_id": 21660383,
  "tariff_multiplier": 30.388932101678613,
  "capacity_delta": 29.094488055163886,
  "objective_function": "objective_function-21660383",
  "created_at": "2013-04-29T00:00:00.000Z",
  "request": {
    "request_id": 6340548
  },
  "quote": {
    "quote_id": 18814871
  }
}


### OptimizationScenario
# @name OptimizationScenario_PATCH
PATCH {{server}}/odata/v4/procurement/OptimizationScenario/21660383
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "scenario_id": 21660383,
  "tariff_multiplier": 30.388932101678613,
  "capacity_delta": 29.094488055163886,
  "objective_function": "objective_function-21660383",
  "created_at": "2013-04-29T00:00:00.000Z",
  "request": {
    "request_id": 6340548
  },
  "quote": {
    "quote_id": 18814871
  }
}


### OptimizationScenario
# @name OptimizationScenario_DELETE
DELETE {{server}}/odata/v4/procurement/OptimizationScenario/21660383
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### ProcurementRequest
# @name ProcurementRequest_GET
GET {{server}}/odata/v4/procurement/ProcurementRequest
Authorization: Basic {{username}}:{{password}}


### ProcurementRequest
# @name ProcurementRequest_POST
POST {{server}}/odata/v4/procurement/ProcurementRequest
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "request_id": 6340548,
 #"requested_qty": 96,
  "status": "us-6340548",
  "raised_by": "raised_by-6340548",
  "created_at": "2014-02-22T00:00:00.000Z",
  "product": {
    "product_id": 6874518
  }
}


### ProcurementRequest
# @name ProcurementRequest_PATCH
PATCH {{server}}/odata/v4/procurement/ProcurementRequest/6340548
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "request_id": 6340548,
  "requested_qty": 96,
  "status": "us-6340548",
  "raised_by": "raised_by-6340548",
  "created_at": "2014-02-22T00:00:00.000Z",
  "product": {
    "product_id": 6874518
  }
}


### ProcurementRequest
# @name ProcurementRequest_DELETE
DELETE {{server}}/odata/v4/procurement/ProcurementRequest/6340548
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### VendorQuote
# @name VendorQuote_GET
GET {{server}}/odata/v4/procurement/VendorQuote
Authorization: Basic {{username}}:{{password}}


### VendorQuote
# @name VendorQuote_POST
POST {{server}}/odata/v4/procurement/VendorQuote
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "quote_id": 18814871,
  "unit_price": 28.63958515050492,
  "capacity_limit": 43,
  "lead_time_days": 98,
  "currency": "currency-18814871",
  "vendor": {
    "vendor_id": 26844173
  },
  "contract": {
    "contract_id": 8690223
  },
  "product": {
    "product_id": 6874518
  }
}


### VendorQuote
# @name VendorQuote_PATCH
PATCH {{server}}/odata/v4/procurement/VendorQuote/18814871
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "quote_id": 18814871,
  "unit_price": 28.63958515050492,
  "capacity_limit": 43,
  "lead_time_days": 98,
  "currency": "currency-18814871",
  "vendor": {
    "vendor_id": 26844173
  },
  "contract": {
    "contract_id": 8690223
  },
  "product": {
    "product_id": 6874518
  }
}


### VendorQuote
# @name VendorQuote_DELETE
DELETE {{server}}/odata/v4/procurement/VendorQuote/18814871
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### KPIprofile
# @name KPIprofile_GET
GET {{server}}/odata/v4/procurement/KPIprofile
Authorization: Basic {{username}}:{{password}}


### KPIprofile
# @name KPIprofile_POST
POST {{server}}/odata/v4/procurement/KPIprofile
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "kpi_id": 11475596,
  "otif_score": 53.30896325013441,
  "logistic_cost": 54.519194807885754,
  "last_updated": "2004-11-29T00:00:00.000Z",
  "vendor_id": 8,
  "vendor_name": "vendor_name-11475596",
  "vendor_risk_rating": 34,
  "vendor_is_compliant": true
}


### KPIprofile
# @name KPIprofile_PATCH
PATCH {{server}}/odata/v4/procurement/KPIprofile/11475596
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "kpi_id": 11475596,
  "otif_score": 53.30896325013441,
  "logistic_cost": 54.519194807885754,
  "last_updated": "2004-11-29T00:00:00.000Z",
  "vendor_id": 8,
  "vendor_name": "vendor_name-11475596",
  "vendor_risk_rating": 34,
  "vendor_is_compliant": true
}


### KPIprofile
# @name KPIprofile_DELETE
DELETE {{server}}/odata/v4/procurement/KPIprofile/11475596
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### ApprovalLog
# @name ApprovalLog_GET
GET {{server}}/odata/v4/procurement/ApprovalLog
Authorization: Basic {{username}}:{{password}}


### ApprovalLog
# @name ApprovalLog_POST
POST {{server}}/odata/v4/procurement/ApprovalLog
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "log_id": 25305303,
  "stage": "stage-25305303",
  "actor_role": "actor_role-25305303",
  "decision": "n-25305303",
  "decided_at": "2022-07-18T00:00:00.000Z",
  "request": {
    "request_id": 6340548
  }
}


### ApprovalLog
# @name ApprovalLog_PATCH
PATCH {{server}}/odata/v4/procurement/ApprovalLog/25305303
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "log_id": 25305303,
  "stage": "stage-25305303",
  "actor_role": "actor_role-25305303",
  "decision": "n-25305303",
  "decided_at": "2022-07-18T00:00:00.000Z",
  "request": {
    "request_id": 6340548
  }
}


### ApprovalLog
# @name ApprovalLog_DELETE
DELETE {{server}}/odata/v4/procurement/ApprovalLog/25305303
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### PlannerComment
# @name PlannerComment_GET
GET {{server}}/odata/v4/procurement/PlannerComment
Authorization: Basic {{username}}:{{password}}


### PlannerComment
# @name PlannerComment_POST
POST {{server}}/odata/v4/procurement/PlannerComment
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "comment_id": 8889495,
  "author_id": "author_id-8889495",
  "text_content": "text_content-8889495",
  "created_at": "2016-06-12T00:00:00.000Z",
  "approval_log": {
    "log_id": 25305303
  },
  "contract": {
    "contract_id": 8690223
  },
  "request": {
    "request_id": 6340548
  },
  "vendor": {
    "vendor_id": 26844173
  }
}


### PlannerComment
# @name PlannerComment_PATCH
PATCH {{server}}/odata/v4/procurement/PlannerComment/8889495
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "comment_id": 8889495,
  "author_id": "author_id-8889495",
  "text_content": "text_content-8889495",
  "created_at": "2016-06-12T00:00:00.000Z",
  "approval_log": {
    "log_id": 25305303
  },
  "contract": {
    "contract_id": 8690223
  },
  "request": {
    "request_id": 6340548
  },
  "vendor": {
    "vendor_id": 26844173
  }
}


### PlannerComment
# @name PlannerComment_DELETE
DELETE {{server}}/odata/v4/procurement/PlannerComment/8889495
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### DecisionOverride
# @name DecisionOverride_GET
GET {{server}}/odata/v4/procurement/DecisionOverride
Authorization: Basic {{username}}:{{password}}


### DecisionOverride
# @name DecisionOverride_POST
POST {{server}}/odata/v4/procurement/DecisionOverride
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "override_id": 11584810,
  "overridden_by": "overridden_by-11584810",
  "new_quantity": 13,
  "created_at": "2003-10-22T00:00:00.000Z",
  "reason_code": "reason_code-11584810",
  "allocation": {
    "allocation_id": 18507107
  }
}


### DecisionOverride
# @name DecisionOverride_PATCH
PATCH {{server}}/odata/v4/procurement/DecisionOverride/11584810
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "override_id": 11584810,
  "overridden_by": "overridden_by-11584810",
  "new_quantity": 13,
  "created_at": "2003-10-22T00:00:00.000Z",
  "reason_code": "reason_code-11584810",
  "allocation": {
    "allocation_id": 18507107
  }
}


### DecisionOverride
# @name DecisionOverride_DELETE
DELETE {{server}}/odata/v4/procurement/DecisionOverride/11584810
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### AgentContext
# @name AgentContext_GET
GET {{server}}/odata/v4/procurement/AgentContext
Authorization: Basic {{username}}:{{password}}


### AgentContext
# @name AgentContext_POST
POST {{server}}/odata/v4/procurement/AgentContext
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "session_id": 9953295,
  "active_constraints": "active_constraints-9953295",
  "last_action": "last_action-9953295",
  "updated_at": "2007-02-07T00:00:00.000Z",
  "request": {
    "request_id": 6340548
  }
}


### AgentContext
# @name AgentContext_PATCH
PATCH {{server}}/odata/v4/procurement/AgentContext/9953295
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "session_id": 9953295,
  "active_constraints": "active_constraints-9953295",
  "last_action": "last_action-9953295",
  "updated_at": "2007-02-07T00:00:00.000Z",
  "request": {
    "request_id": 6340548
  }
}


### AgentContext
# @name AgentContext_DELETE
DELETE {{server}}/odata/v4/procurement/AgentContext/9953295
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### AgentActionLog
# @name AgentActionLog_GET
GET {{server}}/odata/v4/procurement/AgentActionLog
Authorization: Basic {{username}}:{{password}}


### AgentActionLog
# @name AgentActionLog_POST
POST {{server}}/odata/v4/procurement/AgentActionLog
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "action_id": 24801053,
  "action_type": "action_type-24801053",
  "status": "s-24801053",
  "timestamp": "2009-10-23T00:00:00.000Z",
  "context": {
    "session_id": 9953295
  }
}


### AgentActionLog
# @name AgentActionLog_PATCH
PATCH {{server}}/odata/v4/procurement/AgentActionLog/24801053
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "action_id": 24801053,
  "action_type": "action_type-24801053",
  "status": "s-24801053",
  "timestamp": "2009-10-23T00:00:00.000Z",
  "context": {
    "session_id": 9953295
  }
}


### AgentActionLog
# @name AgentActionLog_DELETE
DELETE {{server}}/odata/v4/procurement/AgentActionLog/24801053
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### AgentActionReference
# @name AgentActionReference_GET
GET {{server}}/odata/v4/procurement/AgentActionReference
Authorization: Basic {{username}}:{{password}}


### AgentActionReference
# @name AgentActionReference_POST
POST {{server}}/odata/v4/procurement/AgentActionReference
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "reference_id": 27711218,
  "direction": "n-27711218",
  "ref_type": "ref_type-27711218",
  "ref_id": "ref_id-27711218",
  "snapshot_data": "snapshot_data-27711218",
  "created_at": "2023-02-08T00:00:00.000Z",
  "action": {
    "action_id": 24801053
  }
}


### AgentActionReference
# @name AgentActionReference_PATCH
PATCH {{server}}/odata/v4/procurement/AgentActionReference/27711218
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "reference_id": 27711218,
  "direction": "n-27711218",
  "ref_type": "ref_type-27711218",
  "ref_id": "ref_id-27711218",
  "snapshot_data": "snapshot_data-27711218",
  "created_at": "2023-02-08T00:00:00.000Z",
  "action": {
    "action_id": 24801053
  }
}


### AgentActionReference
# @name AgentActionReference_DELETE
DELETE {{server}}/odata/v4/procurement/AgentActionReference/27711218
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### ProcurementIssue
# @name ProcurementIssue_GET
GET {{server}}/odata/v4/procurement/ProcurementIssue
Authorization: Basic {{username}}:{{password}}


### ProcurementIssue
# @name ProcurementIssue_POST
POST {{server}}/odata/v4/procurement/ProcurementIssue
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "issue_id": 9272279,
  "status": "status-9272279",
  "description": "description-9272279",
  "created_at": "2016-09-15T00:00:00.000Z",
  "resolved_by": "by-9272279",
  "notes": "notes-9272279",
  "purchase_order": {
    "po_id": 12460015
  },
  "vendor": {
    "vendor_id": 26844173
  }
}


### ProcurementIssue
# @name ProcurementIssue_PATCH
PATCH {{server}}/odata/v4/procurement/ProcurementIssue/9272279
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "issue_id": 9272279,
  "status": "status-9272279",
  "description": "description-9272279",
  "created_at": "2016-09-15T00:00:00.000Z",
  "resolved_by": "by-9272279",
  "notes": "notes-9272279",
  "purchase_order": {
    "po_id": 12460015
  },
  "vendor": {
    "vendor_id": 26844173
  }
}


### ProcurementIssue
# @name ProcurementIssue_DELETE
DELETE {{server}}/odata/v4/procurement/ProcurementIssue/9272279
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### ResetProcurementRequests
# @name ResetProcurementRequests_POST
POST {{server}}/odata/v4/procurement/ResetProcurementRequests
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{}
